In [2]:
import pandas as pd

fp = "./data/WEC_Sydney_49.csv"
pd.read_csv(fp)

,X1,Y1,X2,Y2,X3,Y3,X4,Y4,X5,Y5,...,Power42,Power43,Power44,Power45,Power46,Power47,Power48,Power49,qW,Total_Power
0,1.0,1.0,0.00,70.00,1.00,140.00,50.00,198.0,401.0,1.0,...,71909.82,70674.49,70972.33,90957.03,90903.63,87876.82,79499.23,68880.39,0.78,4065416.61
1,598.0,0.0,595.82,77.69,593.70,150.00,549.00,198.0,798.0,0.0,...,68757.68,70665.50,69963.48,84511.25,85691.70,85211.51,76678.20,76119.53,0.76,3951216.37
2,198.0,0.0,197.46,75.19,192.94,150.00,87.64,198.0,398.0,0.0,...,73675.80,77808.44,73519.82,91436.35,88770.60,86632.78,77932.46,69343.12,0.78,4022640.78
3,598.0,0.0,596.97,69.41,592.69,143.80,549.00,198.0,398.0,200.0,...,68947.21,71668.05,69380.67,85191.27,84453.12,85300.41,78573.25,72527.16,0.75,3879223.41
4,198.0,0.0,197.18,79.83,192.97,150.00,89.53,198.0,398.0,0.0,...,78367.97,79075.06,74354.03,85254.75,86978.69,86951.65,77671.87,74901.38,0.77,3974691.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17959,1.0,198.0,50.00,198.00,100.00,198.00,150.00,198.0,201.0,1.0,...,74777.95,75328.19,72050.55,92155.56,89410.09,87942.24,82359.52,69035.90,0.79,4079797.83
17960,398.0,0.0,397.60,72.29,393.00,147.07,349.00,198.0,598.0,0.0,...,70923.77,70611.23,68249.45,90978.35,87013.51,84596.98,76776.71,75651.54,0.75,3909303.33
17961,1.0,1.0,1.00,51.00,1.00,101.00,1.00,151.0,648.0,1.0,...,83075.11,76547.45,76059.62,96899.02,91713.87,88308.28,75781.49,70417.64,0.79,4111341.29
17962,1.0,1.0,1.00,51.00,1.00,101.00,1.00,151.0,648.0,1.0,...,80868.59,76420.36,75312.25,95833.13,92514.46,88406.40,79531.50,70704.51,0.79,4100219.73
17963,198.0,0.0,196.79,73.55,197.18,147.45,149.00,198.0,398.0,0.0,...,70290.22,76572.72,77838.76,86024.36,86504.53,86728.45,79660.05,78190.24,0.77,4011000.25